<a href="https://colab.research.google.com/github/ChristianKitte/HelloNumpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
intro = "Durchlaufen der Übungen für die EA 4"
name = "Christian Kitte"

print(intro + " " + name)

Durchlaufen der Übungen für die EA 4 Christian Kitte


In [3]:
import numpy as np

print(np.__version__)

1.19.5


In [4]:
one_d_array = np.arange(10)
print(one_d_array)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
three_three_bool_array = np.full((3, 3), True, bool)
print(three_three_bool_array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [6]:
arr_input = np.arange(10)
print(arr_input)

arr_output = [x for x in arr_input if x % 2 != 0]
print(arr_output)

arr_output2 = arr_input[arr_input % 2 == 1]
print(arr_output2)

[0 1 2 3 4 5 6 7 8 9]
[1, 3, 5, 7, 9]
[1 3 5 7 9]


In [7]:
arr_input = np.array(range(10))
print(arr_input)

arr_input[arr_input % 2 == 1] = -1
print(arr_input)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [8]:
arr_input = np.array(range(10))
print(arr_input)

arr_output2 = np.where(arr_input % 2 == 1, -1, arr_input)
print(arr_output2)
print(arr_input)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [9]:
arr = np.arange(10)
print(arr)
print(arr.reshape(2, 5))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
print(np.vstack((a, b)))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [11]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
print(np.hstack((a, b)))

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [12]:
a = np.array([1, 2, 3])

print(np.hstack(
    (np.repeat(a[0], 3),
     np.repeat(a[1], 3),
     np.repeat(a[2], 3),
     a, a, a
     )))

print(np.r_[np.repeat(a, 3), np.tile(a, 3)])

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [13]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
print(np.intersect1d(a, b))

[2 4]


In [14]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])
print(np.setdiff1d(a, b))

[1 2 3 4]


In [15]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
print(np.where(a == b))

(array([1, 3, 5, 7]),)


In [16]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(
    a[np.where((a > 4) & (a < 11))]
)

[ 6  9 10]


In [17]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y


def equal(x, y):
    """Get the maximum of two items"""
    if x == y:
        return x
    else:
        return 0


a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

meine_definierte_funktion = np.vectorize(maxx, otypes=[float])
meine_definierte_funktion2 = np.vectorize(equal, otypes=[float])

print(meine_definierte_funktion(a, b))
print(meine_definierte_funktion2(a, b))

[6. 7. 9. 8. 9. 7. 5.]
[0. 0. 0. 8. 0. 0. 0.]


In [18]:
arr = np.arange(9).reshape(3, 3)
print(arr)
print()
print(arr[:, [1, 0, 2]])  #SPALTEN

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [19]:
arr = np.arange(9).reshape(3, 3)
print(arr)
print()
print(arr[[1, 0, 2], :])  # REIHEN

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [20]:
arr = np.arange(9).reshape(3, 3)
print(arr)
print()
print(arr[::-1])  # REIHEN
print()
print(arr[::-1, :])  # zuvor SHORTHAND!

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[6 7 8]
 [3 4 5]
 [0 1 2]]

[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [21]:
arr = np.arange(9).reshape(3, 3)
print(arr)
print()
print(arr[:, ::-1])  # SPALTEN

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [22]:
#arr=np.zeros(15).reshape(5,3)
rand_test1 = np.random.random((5, 3))
rand_test2 = np.random.randint(low=5, high=10, size=(5, 3))
rand_arr = np.random.randint(low=5, high=10, size=(5, 3)) + np.random.random((5, 3))

#print(arr)
print(rand_test1)
print()
print(rand_test2)
print()
print(rand_arr)

[[0.14866772 0.14810765 0.17121055]
 [0.03873917 0.84687332 0.54347247]
 [0.17877541 0.9439081  0.03713227]
 [0.96252013 0.23942334 0.07892238]
 [0.4127592  0.5376751  0.8188826 ]]

[[5 9 6]
 [8 5 5]
 [9 5 6]
 [8 9 7]
 [5 7 8]]

[[9.16608314 6.74561988 5.81096929]
 [9.5449252  7.89378899 8.00154686]
 [7.51949911 7.49049273 9.1687298 ]
 [7.84640096 8.88907696 6.10814757]
 [6.65891567 7.06599336 5.57046616]]


In [23]:
print(np.get_printoptions())
np.set_printoptions(precision=3)
print(np.get_printoptions())

arr = np.random.random((5, 3))
print(arr)

{'edgeitems': 3, 'threshold': 1000, 'floatmode': 'maxprec', 'precision': 8, 'suppress': False, 'linewidth': 75, 'nanstr': 'nan', 'infstr': 'inf', 'sign': '-', 'formatter': None, 'legacy': False}
{'edgeitems': 3, 'threshold': 1000, 'floatmode': 'maxprec', 'precision': 3, 'suppress': False, 'linewidth': 75, 'nanstr': 'nan', 'infstr': 'inf', 'sign': '-', 'formatter': None, 'legacy': False}
[[0.683 0.473 0.214]
 [0.474 0.817 0.624]
 [0.361 0.994 0.363]
 [0.613 0.545 0.276]
 [0.099 0.37  0.716]]


In [24]:
np.random.seed(100)
rand_arr = np.random.random([3, 3]) / 1e3

np.set_printoptions(suppress=False)
print(np.get_printoptions())
print(rand_arr)
print()

np.set_printoptions(suppress=True, precision=6)
print(np.get_printoptions())
print()

rand_arr = np.random.random([3, 3]) / 1e3
print(rand_arr)

{'edgeitems': 3, 'threshold': 1000, 'floatmode': 'maxprec', 'precision': 3, 'suppress': False, 'linewidth': 75, 'nanstr': 'nan', 'infstr': 'inf', 'sign': '-', 'formatter': None, 'legacy': False}
[[5.434e-04 2.784e-04 4.245e-04]
 [8.448e-04 4.719e-06 1.216e-04]
 [6.707e-04 8.259e-04 1.367e-04]]

{'edgeitems': 3, 'threshold': 1000, 'floatmode': 'maxprec', 'precision': 6, 'suppress': True, 'linewidth': 75, 'nanstr': 'nan', 'infstr': 'inf', 'sign': '-', 'formatter': None, 'legacy': False}

[[0.000575 0.000891 0.000209]
 [0.000185 0.000108 0.00022 ]
 [0.000979 0.000812 0.000172]]


In [25]:
a = np.arange(15)
np.set_printoptions(threshold=1000)
print(np.get_printoptions())
print(a)
print()

np.set_printoptions(threshold=6)
print(np.get_printoptions())
print(a)

{'edgeitems': 3, 'threshold': 1000, 'floatmode': 'maxprec', 'precision': 6, 'suppress': True, 'linewidth': 75, 'nanstr': 'nan', 'infstr': 'inf', 'sign': '-', 'formatter': None, 'legacy': False}
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

{'edgeitems': 3, 'threshold': 6, 'floatmode': 'maxprec', 'precision': 6, 'suppress': True, 'linewidth': 75, 'nanstr': 'nan', 'infstr': 'inf', 'sign': '-', 'formatter': None, 'legacy': False}
[ 0  1  2 ... 12 13 14]


In [26]:
np.set_printoptions(threshold=6)
a = np.arange(15)
print(a)
print()

np.set_printoptions(threshold=1000)
print(a)

[ 0  1  2 ... 12 13 14]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [29]:
source = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

print(names)
x = np.genfromtxt(source)
print(x[:3])
print()

x = np.genfromtxt(source, dtype=str)
print(x[:3])
print()

x = np.genfromtxt(source, dtype=str, delimiter=",")
print(x[:3])
print()

x = np.genfromtxt(source, dtype=object, delimiter=",")
print(x[:3])
print()





('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
[nan nan nan]

['5.1,3.5,1.4,0.2,Iris-setosa' '4.9,3.0,1.4,0.2,Iris-setosa'
 '4.7,3.2,1.3,0.2,Iris-setosa']

[['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']]

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]

